### PR TITLE
Update source files with ASF Licenses; Add ASF badge to README.

### PR DESCRIPTION
**Pull request by mrutkows**

### CODE REVIEW

**Review by jberstler — CHANGES_REQUESTED** [review]
@mrutkows is it possible to do this without all the formatting changes? It makes it hard to review the change for mistakes, as well as causes a lot of churn in the history (e.g. `git blame` will lose valuable information for these files).

**Comment by mrutkows** [comment]
@bjustin-ibm Sorry Justin, but the scancode utility (which predated me) enforced no tabs and EOF rules that require all these changes.

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk-sample-matos/pull/1/files?w=1 Ignores white space fwiw.

**Comment by rabbah** [comment]
Historically scan code was only applied to the core repo and to specific files. It is nice to have uniform standards across all the repos but I defer to those actively maintaining and developing all the relevant repos as they're in the best position to evaluate the value of these changes.

**Comment by mrutkows** [comment]
@rabbah @bjustin-ibm please allow this tab to space conversion as it allows us to use scancode unchanged, as well as creates a uniform indentation across the source code; where the indentation is now ad-hoc with some lines using tab and some not.

**Comment by jberstler** [comment]
As stated in other repos, I am all for having coding standards to bring some agreed-upon uniformity to our various code bases. On top of that, these specific changes do seem very reasonable to me.

However... I don't like the idea of rationalizing this kind of massive change by saying that we have a tool that we can't or won't customize. I also don't like that there doesn't seem to be a formalized way for the developer to know exactly what the scancode tool expects, and/or to have a development tool that automatically ensures that changes that cause scancode violations don't appear in the very next commit. Perhaps scancode is or will be integrated into Travis, but I really don't think that it is reasonable to have a process where I commit, push, create a PR, and wait for Travis only to find out I have to _manually_ reformat my code.

As for whether or not this particular PR should be merged, I think @glikson should probably chime in to make that decision.

**Comment by rabbah** [comment]
FWIW I run scan code as a precommit hook. So it will fail locally before I can push any changes. This is in my opinion the way we should be using it (Travis being the safety valve for non conformance). 

I think it checks for tabs instead of spaces, end of line whitespace, missing newline at eof, and confirming/missing license header. I think Matt generalized the license header checks but the core checks are the same. In the future... it would be nice if it also applied code formatting checks and other linters but this is not in scope today.

I think our readme has a mention of the hook but maybe not all these points. It might be worth adding then.

**Review by rabbah — COMMENTED** [review]
Ignoring white space via w=1 the changes are to the headers primarily.

**Comment by jberstler** [comment]
> Ignoring white space via w=1 the changes are to the headers primarily.

Thanks, this is handy!

**Comment by jberstler** [comment]
Additionally, it seems that `git blame -w` will also ignore whitespace changes. This makes massive changes like this much more tolerable.

tmyk

**Comment by mrutkows** [comment]
@bjustin-ibm I am willing and have customized the tool to allow leading indents for GoLang; however, in many of these repos. there is not uniformity from file to file (of the same runtime language type).  Even within the same file some lines use tab indents or not; I am for sane uniformity as different devs. use different editors which treat tab char (replacement) differently and when opening a file should not have to (especially within the same file) see some lines indented differently; this speaks to code readability.  

At min. there should be uniformity in use of tabs in the same file; in the same project it would be much saner to have some standard as one file has it (tabs) and another in the same path does not (same language).  For some languages Tabs are a critical feature (e.g., Go where leading indents are the accepted norm for the community, and in Python tabs are a death sentence as there are stricter implications for line continuation and computational evaluation). 

The first 5 repos. that had scancode enabled when I started this "journey" (not by choice) all happily applied the same rules and everyone seemed fine with having these rules imposed as part of the build process.  Personally, I just want to make sure that each repo. has its rules down for uniformity (even better if they follow what has been established by main openwhisk/catalog, etc.) and can even supply their own .cfg file that reflects it, but we do not even have uniformity within the same path or within even the same file today.

**Comment by glikson** [comment]
I am fine with either option

**Review by jberstler — APPROVED** [review]

**Pull request merged**
